name: Deploy React Application to AWS

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Install dependencies
        run: npm install
      - name: Run tests 
        run: npm run test
      - name: Generate build
        run: npm run build 
      
      - name: Deploy to S3 bucket
        run: |
          aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET }}

      - name: Create invalidation to CloudFront
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.AWS_DIST_ID }} \
          --paths "/*"
