name: REACT CI/CD

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run test
      - run: npm run build